### ISSUE TITLE
你好我有几个问题想问一下

### ISSUE THREAD

**Issue by Insofan** [hsw409328/go-socket#1]
我最近在自学网络编程，懂点Go语言，想用GO写一个简单的手机app服务器，提供json数据，我想问一下学习路线，已经在看Unix 网络编程卷一（套接字）和计算机网络（Tanenbaum关于TCP／IP的），还有什么推荐的书和学习顺序。先写一个简单的不用框架，就用Go原生的库写。

**Comment by hsw409328** [comment]
设计模式，还有就是看开源的框架
